camunda.bpm.client:
  base-url: http://localhost:8080/engine-rest
  lock-duration: 10000
  subscriptions:
    scoreProvider: 
      variable-names: ["LatestDeliveryDate"]
      process-definition-key: ProcessOrderTransportation